# -*- coding: utf-8 -*-
"""BME548_BlurDataSets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PrpNRnv_29ioAPhsvcjaSkl0xxIWfBLi

# Pneumonia Detection — Blurred Dataset Generation

## 1: Clone Repo
"""

!git clone https://github.com/dhruvmenon76/Pneumonia-Detection-Under-Imaging-Constraints.git
!ls Pneumonia-Detection-Under-Imaging-Constraints/data

"""## 2: Imports & Load Data"""

# Commented out IPython magic to ensure Python compatibility.
import sys, os
import torch
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from PIL import Image

# %cd Pneumonia-Detection-Under-Imaging-Constraints
sys.path.append(os.path.abspath('src'))
from dataset_generation import get_dataloaders

BASE_PATH = '/content/Pneumonia-Detection-Under-Imaging-Constraints/data'
print('Folders in data:', os.listdir(BASE_PATH))

train_loader, val_loader, test_loader = get_dataloaders(BASE_PATH, batch_size=32)
print('Train:', len(train_loader.dataset))
print('Val  :', len(val_loader.dataset))
print('Test :', len(test_loader.dataset))

"""## 3: Visualise a Batch"""

images, labels = next(iter(train_loader))
print('Batch shape:', images.shape)

def imshow(img):
    img = img.permute(1, 2, 0) * 0.5 + 0.5
    plt.imshow(img)
    plt.axis('off')

plt.figure(figsize=(10, 6))
for i in range(8):
    plt.subplot(2, 4, i + 1)
    imshow(images[i])
    plt.title('PNEUMONIA' if labels[i].item() == 1 else 'NORMAL')
plt.tight_layout()
plt.show()

"""## 4: Class Distribution"""

def print_class_dist(loader, name):
    lbl = np.array(loader.dataset.labels)
    total = len(lbl)
    n = np.sum(lbl == 0)
    p = np.sum(lbl == 1)
    print(f'\n{name} SET  total={total}  NORMAL={n} ({n/total:.1%})  PNEUMONIA={p} ({p/total:.1%})')

print_class_dist(train_loader, 'TRAIN')
print_class_dist(val_loader,   'VAL')
print_class_dist(test_loader,  'TEST')

"""## 5: Blur Demo (single image, all 3 levels)"""

def gaussian_kernel(size, sigma):
    ax = np.linspace(-(size // 2), size // 2, size)
    xx, yy = np.meshgrid(ax, ax)
    k = np.exp(-(xx**2 + yy**2) / (2 * sigma**2))
    return k / k.sum()

def to_gray(t):
    return np.mean(t.cpu().permute(1, 2, 0).numpy(), axis=2)

img_gray = to_gray(images[4])
configs  = [('Mild  s=1.0', 1.0), ('Medium s=2.5', 2.5), ('Heavy  s=5.0', 5.0)]

plt.figure(figsize=(14, 4))
plt.subplot(1, 4, 1); plt.title('Original'); plt.imshow(img_gray, cmap='gray'); plt.axis('off')
for idx, (title, sigma) in enumerate(configs, 2):
    blurred = cv2.GaussianBlur(img_gray.astype(np.float32), (0, 0), sigmaX=sigma, sigmaY=sigma)
    plt.subplot(1, 4, idx)
    plt.title(title)
    plt.imshow(blurred, cmap='gray')
    plt.axis('off')
plt.tight_layout()
plt.show()

"""## 6: Generate All 3 Blurred Datasets
Creates `data/blur_mild/`, `data/blur_medium/`, `data/blur_heavy/` each with `train/val/test` and `NORMAL/PNEUMONIA` sub-folders.
Safe to re-run — skips files that already exist.
"""

import cv2

BLUR_LEVELS = {
    'blur_mild':   {'sigma': 1.0},
    'blur_medium': {'sigma': 2.5},
    'blur_heavy':  {'sigma': 5.0},
}
SPLITS  = ['train', 'val', 'test']
CLASSES = ['NORMAL', 'PNEUMONIA']

def blur_pil(img, params):
    img = img.resize((224, 224), Image.LANCZOS)
    arr = np.array(img)
    blurred = cv2.GaussianBlur(arr, (0, 0), sigmaX=params['sigma'], sigmaY=params['sigma'])
    return Image.fromarray(blurred)

def generate(base_path, overwrite=True):
    base = Path(base_path)
    for level, params in BLUR_LEVELS.items():
        print(f"\n{'='*55}\n  {level}  sigma={params['sigma']}\n{'='*55}")
        for split in SPLITS:
            for cls in CLASSES:
                src = base / split / cls
                dst = base / level / split / cls
                dst.mkdir(parents=True, exist_ok=True)
                files = list(src.glob('*.jpeg')) + list(src.glob('*.jpg')) + list(src.glob('*.png'))
                if not files:
                    continue
                print(f'  {split}/{cls}  {len(files)} images')
                for i, fp in enumerate(files, 1):
                    out = dst / fp.name
                    if not out.exists() or overwrite:
                        blur_pil(Image.open(fp).convert('RGB'), params).save(out)
                    if i % 200 == 0 or i == len(files):
                        print(f'    {i}/{len(files)}', end='\r')
                print()
        print(f'  {level} done.')
    print('\nAll 3 blurred datasets created!')

BASE_PATH = '/content/Pneumonia-Detection-Under-Imaging-Constraints/data'
generate(BASE_PATH)

"""## 7: Verify Counts"""

def count(path):
    p = Path(path)
    return len(list(p.glob('*.jpeg')) + list(p.glob('*.jpg')) + list(p.glob('*.png')))

base = Path(BASE_PATH)
datasets = ['original'] + list(BLUR_LEVELS.keys())
print(f"{'Dataset':<20} {'Split':<8} {'NORMAL':>8} {'PNEUMONIA':>12} {'Total':>8}")
print('='*60)
for ds in datasets:
    for split in SPLITS:
        prefix = base if ds == 'original' else base / ds
        n = count(prefix / split / 'NORMAL')
        p = count(prefix / split / 'PNEUMONIA')
        print(f'{ds:<20} {split:<8} {n:>8} {p:>12} {n+p:>8}')
    print('-'*60)

BASE = '/content/Pneumonia-Detection-Under-Imaging-Constraints/data'

# Pick one image from NORMAL and one from PNEUMONIA
sample_normal    = list((Path(BASE) / 'test' / 'NORMAL').glob('*.jpeg'))[0]
sample_pneumonia = list((Path(BASE) / 'test' / 'PNEUMONIA').glob('*.jpeg'))[0]

datasets = ['original', 'blur_mild', 'blur_medium', 'blur_heavy']

fig, axes = plt.subplots(2, 4, figsize=(16, 8))

for col, ds in enumerate(datasets):
    # NORMAL row
    path_n = Path(BASE) / ds / 'test' / 'NORMAL' / sample_normal.name if ds != 'original' else sample_normal
    axes[0, col].imshow(Image.open(path_n).convert('L'), cmap='gray')
    axes[0, col].set_title(f'{ds}\nNORMAL')
    axes[0, col].axis('off')

    # PNEUMONIA row
    path_p = Path(BASE) / ds / 'test' / 'PNEUMONIA' / sample_pneumonia.name if ds != 'original' else sample_pneumonia
    axes[1, col].imshow(Image.open(path_p).convert('L'), cmap='gray')
    axes[1, col].set_title(f'{ds}\nPNEUMONIA')
    axes[1, col].axis('off')

plt.suptitle('Original vs Blurred Datasets — same image across all levels', fontsize=13)
plt.tight_layout()
plt.show()

"""## 8: Training Model from Github

"""

import copy, time,
import torch.nn as nn
import torch.optim as optim
from torchvision.models import densenet121
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, roc_auc_score, confusion_matrix)

sys.path.append(os.path.abspath('src'))
from dataset_generation import get_dataloaders

base_path  = '/content/Pneumonia-Detection-Under-Imaging-Constraints/data'
device     = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
batch_size = 32
num_epochs = 8
lr         = 1e-4

# Load CLEAN original data for training
train_loader, val_loader, test_loader = get_dataloaders(base_path, batch_size=batch_size)

# Class weights
train_labels    = np.array(train_loader.dataset.labels)
num_normal      = np.sum(train_labels == 0)
num_pneumonia   = np.sum(train_labels == 1)
total           = len(train_labels)
class_weights   = torch.tensor(
    [total / (2 * num_normal), total / (2 * num_pneumonia)],
    dtype=torch.float32
).to(device)

# Build DenseNet121
model = densenet121(weights=None)
model.classifier = nn.Linear(model.classifier.in_features, 2)
model = model.to(device)

criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)

# Training loop
best_model_wts = copy.deepcopy(model.state_dict())
best_val_loss  = float('inf')

for epoch in range(num_epochs):
    model.train()
    running_loss, correct, total_seen = 0.0, 0, 0
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * images.size(0)
        correct      += (torch.argmax(outputs, 1) == labels).sum().item()
        total_seen   += labels.size(0)

    # Check val loss to save best model
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            val_loss += criterion(model(images), labels).item() * images.size(0)
    val_loss /= len(val_loader.dataset)

    if val_loss < best_val_loss:
        best_val_loss  = val_loss
        best_model_wts = copy.deepcopy(model.state_dict())

    print(f"Epoch {epoch+1:02d}/{num_epochs} | "
          f"Train Loss: {running_loss/len(train_loader.dataset):.4f} | "
          f"Train Acc: {correct/total_seen:.4f} | Val Loss: {val_loss:.4f}")

# Load best weights and save
model.load_state_dict(best_model_wts)
torch.save(model.state_dict(), 'best_model.pth')
print("\nModel trained and saved to best_model.pth")

"""## 9: Testing on Blurred Datasets

"""

from torch.utils.data import DataLoader
from torchvision import transforms
from sklearn.metrics import ConfusionMatrixDisplay, balanced_accuracy_score

# ── Blur transform ──────────────────────────────────────────
class GaussianBlurTransform:
    def __init__(self, sigma=0.0, image_size=(224, 224)):
        self.sigma      = sigma
        self.image_size = image_size

    def __call__(self, img):
        img = img.resize(self.image_size, Image.LANCZOS)
        if self.sigma == 0.0:
            return img
        arr     = np.array(img)
        blurred = cv2.GaussianBlur(arr, (0, 0), sigmaX=self.sigma, sigmaY=self.sigma)
        return Image.fromarray(blurred)

def build_blur_transform(sigma):
    return transforms.Compose([
        GaussianBlurTransform(sigma=sigma),
        transforms.ToTensor(),
        transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])
    ])

def clone_with_transform(dataset, transform):
    ds = copy.deepcopy(dataset)
    ds.transform = transform
    return ds

# ── Evaluation function ─────────────────────────────────────
def evaluate(model, loader):
    model.eval()
    all_labels, all_preds, all_probs = [], [], []
    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device)
            outputs = model(images)
            probs   = torch.softmax(outputs, dim=1)[:, 1].cpu().numpy()
            preds   = torch.argmax(outputs, dim=1).cpu().numpy()
            all_labels.extend(labels.numpy())
            all_preds.extend(preds)
            all_probs.extend(probs)
    all_labels = np.array(all_labels)
    all_preds  = np.array(all_preds)
    return {
        'accuracy':  accuracy_score(all_labels, all_preds),
        'f1':        f1_score(all_labels, all_preds, zero_division=0),
        'recall':    recall_score(all_labels, all_preds, zero_division=0),
        'precision': precision_score(all_labels, all_preds, zero_division=0),
        'auc':       roc_auc_score(all_labels, all_probs),
        'cm':        confusion_matrix(all_labels, all_preds),
        'bal_acc':   balanced_accuracy_score(all_labels, all_preds),
    }

# ── Run evaluation across all blur levels ───────────────────
blur_levels = {'clean': 0.0, 'mild': 1.0, 'medium': 2.5, 'heavy': 5.0}
results     = {}

for name, sigma in blur_levels.items():
    transform   = build_blur_transform(sigma)
    test_ds     = clone_with_transform(test_loader.dataset, transform)
    test_dl     = DataLoader(test_ds, batch_size=32, shuffle=False, num_workers=2)
    results[name] = evaluate(model, test_dl)
    print(f"{name:<8} | Acc={results[name]['accuracy']:.4f} | "
          f"F1={results[name]['f1']:.4f} | AUC={results[name]['auc']:.4f} | "
          f"Recall={results[name]['recall']:.4f}")

# ── Summary table ────────────────────────────────────────────
print(f"\n{'Dataset':<10} {'Accuracy':>10} {'F1':>8} {'AUC':>8} {'Recall':>8} {'Precision':>10} {'Bal Acc':>10}")
print('='*70)
for name, r in results.items():
    print(f"{name:<10} {r['accuracy']:>10.4f} {r['f1']:>8.4f} "
          f"{r['auc']:>8.4f} {r['recall']:>8.4f} {r['precision']:>10.4f} {r['bal_acc']:>10.4f}")

# ── Confusion matrices ────────────────────────────────────────
fig, axes = plt.subplots(1, 4, figsize=(18, 4))
for ax, (name, r) in zip(axes, results.items()):
    ConfusionMatrixDisplay(r['cm'], display_labels=['NORMAL', 'PNEUMONIA']).plot(ax=ax, colorbar=False)
    ax.set_title(f"{name}\nAcc={r['accuracy']:.3f}  F1={r['f1']:.3f}")
plt.tight_layout()
plt.show()

# ── Accuracy drop bar chart ───────────────────────────────────
plt.figure(figsize=(8, 4))
names = list(results.keys())
accs  = [results[n]['accuracy'] for n in names]
bars  = plt.bar(names, accs, color=['steelblue', 'orange', 'tomato', 'firebrick'])
for bar, acc in zip(bars, accs):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
             f'{acc:.3f}', ha='center')
plt.ylim(0, 1)
plt.ylabel('Accuracy')
plt.title('DenseNet121 Accuracy vs Blur Level')
plt.tight_layout()
plt.show()